base/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import include
from django.urls import path

from . import settings
from .views import home

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home, name="home"),
    path('orders/lite/', include('orders_lite.urls')),
    path('accounts/', include('accounts.urls')),
    path('locations/', include('locations.urls')),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

locations/urls.py
# /locations/urls.py
from django.conf.urls.static import static
from django.urls import path

from base import settings
from . import views

app_name = 'locations'

urlpatterns = [
    path('', views.locations, name="home"),
    path('g/', views.gbay_locations, name="gbay_locations"),
    path('c/', views.c_locations, name="c_locations"),
    path('b/', views.b_locations, name="b_locations"),
    path('cc/', views.cc_locations, name="cc_locations"),
    path('bph/', views.bph_locations, name="bph_locations"),
    path('cph/', views.cph_locations, name="cph_locations"),
    path('nwr/', views.nwr_locations, name="nwr_locations"),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

locations/models.py
from django.db import models
from django.template.defaultfilters import slugify


class Location(models.Model):
    created = models.DateTimeField(auto_now_add=True)
    name = models.CharField(max_length=200, blank=True, null=True)
    barcode = models.ImageField(blank=True, null=True)
    slug = models.SlugField(blank=True, null=True)


class GBayLocation(Location):
    loc_isle = models.IntegerField(null=True)
    loc_column = models.IntegerField(null=True)
    loc_row = models.IntegerField(null=True)

    class Meta:
        ordering = ['name']
        verbose_name_plural = "G Locations"
        verbose_name = "G Location"

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):

        self.name = f"G {str(self.loc_isle).zfill(2)}-{str(self.loc_column).zfill(2)}-{str(self.loc_row).zfill(2)}"
        self.barcode = f"G/G{str(self.loc_isle).zfill(2)}-{str(self.loc_column).zfill(2)}-{str(self.loc_row).zfill(2)}.png"
        self.slug = slugify(self.name)
        super(GBayLocation, self).save(*args, **kwargs)


class CLocation(Location):
    loc_column = models.IntegerField(null=True)
    loc_row = models.IntegerField(null=True)

    class Meta:
        ordering = ['name']
        verbose_name_plural = "C Locations"
        verbose_name = "C Location"

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):

        self.name = f"C{str(self.loc_column).zfill(2)}-{str(self.loc_row).zfill(2)}"
        self.barcode = f"C/C{str(self.loc_column).zfill(2)}-{str(self.loc_row).zfill(2)}.png"
        self.slug = slugify(self.name)
        super(CLocation, self).save(*args, **kwargs)


class BLocation(Location):
    loc_column = models.IntegerField(null=True)
    loc_row = models.IntegerField(null=True)

    class Meta:
        ordering = ['name']
        verbose_name_plural = "B Locations"
        verbose_name = "B Location"

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):

        self.name = f"B{str(self.loc_column).zfill(2)}-{str(self.loc_row).zfill(2)}"
        self.barcode = f"B/B{str(self.loc_column).zfill(2)}-{str(self.loc_row).zfill(2)}.png"
        self.slug = slugify(self.name)
        super(BLocation, self).save(*args, **kwargs)


class CCLocation(Location):
    loc_row = models.IntegerField(null=True)

    class Meta:
        ordering = ['name']
        verbose_name_plural = "CC Locations"
        verbose_name = "CC Location"

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):

        self.name = f"CC-{str(self.loc_row).zfill(2)}"
        self.barcode = f"CC/CC-{str(self.loc_row).zfill(2)}.png"
        self.slug = slugify(self.name)
        super(CCLocation, self).save(*args, **kwargs)


class BPHLocation(Location):
    loc_column = models.IntegerField(null=True)
    loc_row = models.IntegerField(null=True)

    class Meta:
        ordering = ['name']
        verbose_name_plural = "BPH Locations"
        verbose_name = "BPH Location"

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):

        self.name = f"BPH-{str(self.loc_column).zfill(2)}-{str(self.loc_row).zfill(2)}"
        self.barcode = f"BPH/BPH-{str(self.loc_column).zfill(2)}-{str(self.loc_row).zfill(2)}.png"
        self.slug = slugify(self.name)
        super(BPHLocation, self).save(*args, **kwargs)


class CPHLocation(Location):
    loc_column = models.IntegerField(null=True)
    loc_row = models.IntegerField(null=True)

    class Meta:
        ordering = ['name']
        verbose_name_plural = "CPH Locations"
        verbose_name = "CPH Location"

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):

        self.name = f"CPH-{str(self.loc_column).zfill(2)}-{str(self.loc_row).zfill(2)}"
        self.barcode = f"CPH/CPH-{str(self.loc_column).zfill(2)}-{str(self.loc_row).zfill(2)}.png"
        self.slug = slugify(self.name)
        super(CPHLocation, self).save(*args, **kwargs)


class NWRLocation(Location):
    loc_column = models.IntegerField(null=True)
    loc_row = models.IntegerField(null=True)

    class Meta:
        ordering = ['name']
        verbose_name_plural = "NWR Locations"
        verbose_name = "NWR Location"

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):

        self.name = f"NWR-{str(self.loc_column).zfill(2)}-{str(self.loc_row).zfill(2)}"
        self.barcode = f"NWR/NWR-{str(self.loc_column).zfill(2)}-{str(self.loc_row).zfill(2)}.png"
        self.slug = slugify(self.name)
        super(NWRLocation, self).save(*args, **kwargs)

base/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required


@login_required(login_url="/accounts/login/")
def home(request):
    context = {}
    return render(request, 'home.html', context)

locations/views.py
# /locations/views.py
from django.db.models import Q
from django.shortcuts import render

from .models import GBayLocation, CCLocation, CLocation, CPHLocation, BLocation, BPHLocation, NWRLocation


def locations(request):
    context = {}
    return render(request, 'locations/locations.html', context)


def gbay_locations(request):
    def is_valid_query_param(param):
        return param != "" and param is not None

    qs = GBayLocation.objects.all()
    contains_isle_query = request.GET.get('contains_isle')
    contains_col_query = request.GET.get('contains_col')
    contains_row_query = request.GET.get('contains_row')

    if is_valid_query_param(contains_isle_query):
        qs = qs.filter(Q(loc_isle__iexact=contains_isle_query)).distinct()
    if is_valid_query_param(contains_col_query):
        qs = qs.filter(Q(loc_column__iexact=contains_col_query)).distinct()
    if is_valid_query_param(contains_row_query):
        qs = qs.filter(Q(loc_row__iexact=contains_row_query)).distinct()

    context = {
        "qs": qs,
    }
    return render(request, 'locations/gbay_locations.html', context)


def c_locations(request):
    def is_valid_query_param(param):
        return param != "" and param is not None

    qs = CLocation.objects.all()
    contains_col_query = request.GET.get('contains_col')
    contains_row_query = request.GET.get('contains_row')

    if is_valid_query_param(contains_col_query):
        qs = qs.filter(Q(loc_column__iexact=contains_col_query)).distinct()
    if is_valid_query_param(contains_row_query):
        qs = qs.filter(Q(loc_row__iexact=contains_row_query)).distinct()

    context = {
        "qs": qs,
    }
    return render(request, 'locations/c_locations.html', context)


def b_locations(request):
    def is_valid_query_param(param):
        return param != "" and param is not None

    qs = BLocation.objects.all()
    contains_col_query = request.GET.get('contains_col')
    contains_row_query = request.GET.get('contains_row')

    if is_valid_query_param(contains_col_query):
        qs = qs.filter(Q(loc_column__iexact=contains_col_query)).distinct()
    if is_valid_query_param(contains_row_query):
        qs = qs.filter(Q(loc_row__iexact=contains_row_query)).distinct()

    context = {
        "qs": qs,
    }
    return render(request, 'locations/b_locations.html', context)


def cc_locations(request):
    def is_valid_query_param(param):
        return param != "" and param is not None

    qs = CCLocation.objects.all()
    contains_row_query = request.GET.get('contains_row')

    if is_valid_query_param(contains_row_query):
        qs = qs.filter(Q(loc_row__iexact=contains_row_query)).distinct()

    context = {
        "qs": qs,
    }
    return render(request, 'locations/cc_locations.html', context)


def bph_locations(request):
    def is_valid_query_param(param):
        return param != "" and param is not None

    qs = BPHLocation.objects.all()
    contains_col_query = request.GET.get('contains_col')
    contains_row_query = request.GET.get('contains_row')

    if is_valid_query_param(contains_col_query):
        qs = qs.filter(Q(loc_column__iexact=contains_col_query)).distinct()
    if is_valid_query_param(contains_row_query):
        qs = qs.filter(Q(loc_row__iexact=contains_row_query)).distinct()

    context = {
        "qs": qs,
    }
    return render(request, 'locations/bph_locations.html', context)


def cph_locations(request):
    def is_valid_query_param(param):
        return param != "" and param is not None

    qs = CPHLocation.objects.all()
    contains_col_query = request.GET.get('contains_col')
    contains_row_query = request.GET.get('contains_row')

    if is_valid_query_param(contains_col_query):
        qs = qs.filter(Q(loc_column__iexact=contains_col_query)).distinct()
    if is_valid_query_param(contains_row_query):
        qs = qs.filter(Q(loc_row__iexact=contains_row_query)).distinct()

    context = {
        "qs": qs,
    }
    return render(request, 'locations/bph_locations.html', context)


def nwr_locations(request):
    def is_valid_query_param(param):
        return param != "" and param is not None

    qs = NWRLocation.objects.all()
    contains_col_query = request.GET.get('contains_col')
    contains_row_query = request.GET.get('contains_row')

    if is_valid_query_param(contains_col_query):
        qs = qs.filter(Q(loc_column__iexact=contains_col_query)).distinct()
    if is_valid_query_param(contains_row_query):
        qs = qs.filter(Q(loc_row__iexact=contains_row_query)).distinct()

    context = {
        "qs": qs,
    }
    return render(request, 'locations/nwr_locations.html', context)

locations/templates/locations/b_locations.html
<!-- /locations/templates/locations/home.html -->
{% extends 'base.html' %}
{% load static %}

{% block content %}

    <div class="container-fluid mt-4">
        <h3 class='text-center'>ALRO B</h3>
    </div>
    <div class="container-fluid">
        <form>
            <div class="row">
                <div class="col">
                    <input name="contains_col" type="number" class="form-control" placeholder="Col...">
                </div>
                <div class="col">
                    <input name="contains_row" type="number" class="form-control" placeholder="Row...">
                </div>
                <button type="submit" class="btn btn-primary btn-lg btn-block m-3">Search</button>
            </div>
        </form>
    </div>
    {% for location in qs.all %}
        <div class="row text-center m-3">
            <div class="container-fluid col-sm-12 col-md-6 offset-md-3 col-lg-4 offset-lg-4 card">
                <img src="{{ location.barcode.url }}" alt="{{ location.name }}">
            </div>

        </div>
    {% endfor %}


{% endblock content %}

locations/templates/locations/base.html
<!-- /locations/templates/locations/base.html -->
{% load static %} {% load humanize %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    <!-- font awesome -->
    <script src="https://kit.fontawesome.com/b4ac6ef2b3.js"></script>
    <!--Import Google Icon Font-->
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet" />

    {% comment %} <!-- Compiled and minified CSS -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css"> {% endcomment %}

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <!-- Custom SASS (CSS) File -->
    <link rel="stylesheet" href="{% static 'locations/css/locations.css' %}">

    <title>locations</title>
</head>
<header>

</header>

<body>

    {% block content %} {% endblock content %}

    {% comment %} <!-- Compiled Jquery -->
    <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
    <!-- Compiled and minified JavaScript -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script> {% endcomment %}

    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

    <script src="{% static 'locations/js/locations.js' %}"></script>
</body>

</html>

locations/templates/locations/bph_locations.html
<!-- /locations/templates/locations/home.html -->
{% extends 'base.html' %}
{% load static %}

{% block content %}

    <div class="container-fluid mt-4">
        <h3 class='text-center'>ALRO BPH</h3>
    </div>
    <div class="container-fluid">
        <form>
            <div class="row">
                <div class="col">
                    <input name="contains_col" type="number" class="form-control" placeholder="Col...">
                </div>
                <div class="col">
                    <input name="contains_row" type="number" class="form-control" placeholder="Row...">
                </div>
                <button type="submit" class="btn btn-primary btn-lg btn-block m-3">Search</button>
            </div>
        </form>
    </div>
    {% for location in qs.all %}
        <div class="row text-center m-3">
            <div class="container-fluid col-sm-12 col-md-6 offset-md-3 col-lg-4 offset-lg-4 card">
                <img src="{{ location.barcode.url }}" alt="{{ location.name }}">
            </div>

        </div>
    {% endfor %}


{% endblock content %}

locations/templates/locations/c_locations.html
<!-- /locations/templates/locations/home.html -->
{% extends 'base.html' %}
{% load static %}

{% block content %}

    <div class="container-fluid mt-4">
        <h3 class='text-center'>ALRO C</h3>
    </div>
    <div class="container-fluid">
        <form>
            <div class="row">
                <div class="col">
                    <input name="contains_col" type="number" class="form-control" placeholder="Col...">
                </div>
                <div class="col">
                    <input name="contains_row" type="number" class="form-control" placeholder="Row...">
                </div>
                <button type="submit" class="btn btn-primary btn-lg btn-block m-3">Search</button>
            </div>
        </form>
    </div>
    {% for location in qs.all %}
        <div class="row text-center m-3">
            <div class="container-fluid col-sm-12 col-md-6 offset-md-3 col-lg-4 offset-lg-4 card">
                <img src="{{ location.barcode.url }}" alt="{{ location.name }}">
            </div>

        </div>
    {% endfor %}


{% endblock content %}

locations/templates/locations/cc_locations.html
<!-- /locations/templates/locations/home.html -->
{% extends 'base.html' %}
{% load static %}

{% block content %}

    <div class="container-fluid mt-4">
        <h3 class='text-center'>ALRO CC</h3>
    </div>
    <div class="container-fluid">
        <form>
            <div class="row">
                <div class="col">
                    <input name="contains_row" type="number" class="form-control" placeholder="Row...">
                </div>
                <button type="submit" class="btn btn-primary btn-lg btn-block m-3">Search</button>
            </div>
        </form>
    </div>
    {% for location in qs.all %}
        <div class="row text-center m-3">
            <div class="container-fluid col-sm-12 col-md-6 offset-md-3 col-lg-4 offset-lg-4 card">
                <img src="{{ location.barcode.url }}" alt="{{ location.name }}">
            </div>

        </div>
    {% endfor %}


{% endblock content %}

locations/templates/locations/cph_locations.html
<!-- /locations/templates/locations/home.html -->
{% extends 'base.html' %}
{% load static %}

{% block content %}

    <div class="container-fluid mt-4">
        <h3 class='text-center'>ALRO CPH</h3>
    </div>
    <div class="container-fluid">
        <form>
            <div class="row">
                <div class="col">
                    <input name="contains_col" type="number" class="form-control" placeholder="Col...">
                </div>
                <div class="col">
                    <input name="contains_row" type="number" class="form-control" placeholder="Row...">
                </div>
                <button type="submit" class="btn btn-primary btn-lg btn-block m-3">Search</button>
            </div>
        </form>
    </div>
    {% for location in qs.all %}
        <div class="row text-center m-3">
            <div class="container-fluid col-sm-12 col-md-6 offset-md-3 col-lg-4 offset-lg-4 card">
                <img src="{{ location.barcode.url }}" alt="{{ location.name }}">
            </div>

        </div>
    {% endfor %}


{% endblock content %}

locations/templates/locations/gbay_locations.html
<!-- /locations/templates/locations/home.html -->
{% extends 'base.html' %}
{% load static %}

{% block content %}

    <div class="container-fluid mt-4">
        <h3 class='text-center'>ALRO G Bay</h3>
    </div>
    <div class="container-fluid">
        <form>
            <div class="row">
                <div class="col">
                    <input name="contains_isle" type="number" class="form-control" placeholder="Isle...">
                </div>
                <div class="col">
                    <input name="contains_col" type="number" class="form-control" placeholder="Col...">
                </div>
                <div class="col">
                    <input name="contains_row" type="number" class="form-control" placeholder="Row...">
                </div>
                <button type="submit" class="btn btn-primary btn-lg btn-block m-3">Search</button>
            </div>
        </form>
    </div>
    {% for location in qs %}
        <div class="row text-center m-3">
            <div class="container-fluid col-sm-12 col-md-6 offset-md-3 col-lg-4 offset-lg-4 card">
                <img src="{{ location.barcode.url }}" alt="{{ location.name }}">
            </div>

        </div>
    {% endfor %}


{% endblock content %}

locations/templates/locations/locations.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

    <div class="container-fluid">
        <div class="row text-center">
            <div class="col-sm3 p-3">
                <a class="p-3 btn-sm btn btn-primary" href="{% url 'locations:gbay_locations' %}">G</a>
            </div><div class="col-sm3 p-3">
                <a class="p-3 btn-sm btn btn-primary" href="{% url 'locations:c_locations' %}">C</a>
            </div>
            <div class="col-sm3 p-3">
                <a class="p-3 btn-sm btn btn-primary" href="{% url 'locations:b_locations' %}">B</a>
            </div><div class="col-sm3 p-3">
                <a class="p-3 btn-sm btn btn-primary" href="{% url 'locations:cc_locations' %}">CC</a>
            </div>
            <div class="col-sm3 p-3">
                <a class="p-3 btn-sm btn btn-primary" href="{% url 'locations:bph_locations' %}">BPH</a>
            </div>
            <div class="col-sm3 p-3">
                <a class="p-3 btn-sm btn btn-primary" href="{% url 'locations:cph_locations' %}">CPH</a>
            </div>
            <div class="col-sm3 p-3">
                <a class="p-3 btn-sm btn btn-primary" href="{% url 'locations:nwr_locations' %}">NWR</a>
            </div>
        </div>
    </div>
    </div>

{% endblock content %}

locations/templates/locations/nwr_locations.html
<!-- /locations/templates/locations/home.html -->
{% extends 'base.html' %}
{% load static %}

{% block content %}

    <div class="container-fluid mt-4">
        <h3 class='text-center'>ALRO NWR</h3>
    </div>
    <div class="container-fluid">
        <form>
            <div class="row">
                <div class="col">
                    <input name="contains_col" type="number" class="form-control" placeholder="Col...">
                </div>
                <div class="col">
                    <input name="contains_row" type="number" class="form-control" placeholder="Row...">
                </div>
                <button type="submit" class="btn btn-primary btn-lg btn-block m-3">Search</button>
            </div>
        </form>
    </div>
    {% for location in qs.all %}
        <div class="row text-center m-3">
            <div class="container-fluid col-sm-12 col-md-6 offset-md-3 col-lg-4 offset-lg-4 card">
                <img src="{{ location.barcode.url }}" alt="{{ location.name }}">
            </div>

        </div>
    {% endfor %}


{% endblock content %}