base/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import include
from django.urls import path

from . import settings
from .views import home

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home, name="home"),
    path('orders/lite/', include('orders_lite.urls')),
    path('accounts/', include('accounts.urls')),
    path('locations/', include('locations.urls')),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

orders_lite/urls.py
# /orders_lite/urls.py
from django.conf.urls.static import static
from django.urls import path, include
from base import settings
from orders_lite.views import home, order_edit, order_duplicate, order_create, order_delete, order_detail

app_name = 'orders_lite'

urlpatterns = [
    path('', home, name="home"),
    path('create/', order_create, name='order_create'),
    path('<slug:slug>/', order_detail, name='order_detail'),
    path('<slug:slug>/edit/', order_edit, name='order_edit'),
    path('<slug:slug>/duplicate/', order_duplicate, name='order_duplicate'),
    path('<slug:slug>/delete/', order_delete, name='order_delete'),
]

orders_lite/models.py
from django.db import models
from django.template.defaultfilters import slugify
from django.utils.timezone import now as today
from orders_lite.create_ct_rt_barcodes import barcode, saw_barcode
from locations.models import BLocation, CLocation, CCLocation, GBayLocation, CPHLocation, BPHLocation, NWRLocation


class Material(models.Model):
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    material_name = models.CharField(max_length=200, blank=True, null=True)
    material_type = models.CharField(max_length=50, blank=True, null=True)
    density = models.FloatField(null=True)
    slug = models.SlugField(blank=True, null=True)

    class Meta:
        ordering = ['material_name']
        verbose_name_plural = "Materials"
        verbose_name = "Material"

    def __str__(self):
        return self.material_name

    def save(self, *args, **kwargs):
        self.slug = slugify(self.material_name)
        super(Material, self).save(*args, **kwargs)


class Wave(models.Model):
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    name = models.CharField(max_length=200, blank=True, null=True)
    color = models.CharField(max_length=10, blank=True, null=True)
    ship_time = models.TimeField(auto_now=False, auto_now_add=False)
    priority = models.IntegerField(null=True)
    slug = models.SlugField(blank=True, null=True)

    class Meta:
        ordering = ['priority']
        verbose_name_plural = "Waves"
        verbose_name = "Wave"

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super(Wave, self).save(*args, **kwargs)


class Location(models.Model):
    BIN_TYPES = (
        ("G", "G Bay"),
        ("B", "B"),
        ("NWR", "NWR"),
        ("C", "C"),
        ("CC", "CC"),
        ("CPH", "CPH"),
        ("BPH", "BPH"),
    )
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    bin_type = models.CharField(max_length=200, blank=True, null=True, choices=BIN_TYPES)
    if bin_type == "G":
        bin = models.ForeignKey(GBayLocation, on_delete=models.CASCADE)
    elif bin_type == "B":
        bin = models.ForeignKey(BLocation, on_delete=models.CASCADE)
    elif bin_type == "NWR":
        bin = models.ForeignKey(NWRLocation, on_delete=models.CASCADE)
    elif bin_type == "C":
        bin = models.ForeignKey(CLocation, on_delete=models.CASCADE)
    elif bin_type == "CC":
        bin = models.ForeignKey(CCLocation, on_delete=models.CASCADE)
    elif bin_type == "CPH":
        bin = models.ForeignKey(CPHLocation, on_delete=models.CASCADE)
    elif bin_type == "BPH":
        bin = models.ForeignKey(BPHLocation, on_delete=models.CASCADE)
    name = models.CharField(max_length=200, blank=True, null=True)
    slug = models.SlugField(blank=True, null=True)

    class Meta:
        ordering = ['id']
        verbose_name_plural = "Locations"
        verbose_name = "Location"

    def __str__(self):
        return self.bin_type

    def save(self, *args, **kwargs):
        self.name = f"{self.bin_type} {self.isle}-{self.column}-{self.row}"
        self.slug = slugify(self.bin_type)
        super(Location, self).save(*args, **kwargs)


class Saw(models.Model):
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    name = models.CharField(max_length=200, blank=True, null=True)

    class Meta:
        ordering = ['name']
        verbose_name_plural = "Saws"
        verbose_name = "Saw"

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super(Saw, self).save(*args, **kwargs)


class Order(models.Model):
    created = models.DateTimeField(auto_now_add=True)
    name = models.CharField(max_length=200, blank=True, null=True)
    due_date = models.DateField(null=True)
    ct = models.IntegerField(null=True)
    ct_barcode = models.ImageField(blank=True, null=True)
    rt = models.IntegerField(null=True)
    rt_barcode = models.ImageField(blank=True, null=True)
    wave = models.ForeignKey(Wave, on_delete=models.CASCADE)
    bin_name = models.CharField(max_length=200, blank=True, null=True)
    bin = models.ForeignKey(Location, default=0, on_delete=models.CASCADE)
    bin_isle = models.IntegerField(null=True)
    bin_column = models.IntegerField(null=True)
    bin_row = models.IntegerField(null=True)
    bin_barcode = models.ImageField(blank=True, null=True)
    saw = models.ForeignKey(Saw, on_delete=models.CASCADE)
    saw_barcode = models.ImageField(blank=True, null=True)
    material = models.ForeignKey(Material, on_delete=models.CASCADE)
    thickness = models.FloatField(null=True, blank=True)
    width = models.FloatField(null=True, blank=True)
    length = models.FloatField(null=True, blank=True)
    pulled = models.BooleanField(default=False)
    delivered = models.BooleanField(default=False)
    stock_ran = models.BooleanField(default=False)
    slug = models.SlugField(blank=True, null=True)

    class Meta:
        ordering = ['due_date']
        verbose_name_plural = "Orders"
        verbose_name = "Order"

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        barcode(self.ct, "CT")
        barcode(self.rt, "RT")
        bin_number = f"{str(self.bin_isle).zfill(2)}-{str(self.bin_column).zfill(2)}-{str(self.bin_row).zfill(2)}"
        barcode(bin_number, "G")
        saw_barcode(self.saw)

        self.thickness = 0
        self.width = 0
        self.length = 0

        self.ct_barcode = f"CT/CT{self.ct}.png"
        self.rt_barcode = f"RT/RT{self.rt}.png"
        self.saw_barcode = f"SAWS/{self.saw}.png"
        self.bin_barcode = f"G/{self.bin_name}.png"

        self.name = f"CT{self.ct} - RT{self.rt}"
        self.bin_name = f"{self.bin}{str(self.bin_isle).zfill(2)}-{str(self.bin_column).zfill(2)}-{str(self.bin_row).zfill(2)}"

        self.slug = slugify(self.name)
        super(Order, self).save(*args, **kwargs)

orders_lite/forms.py
from django import forms
from . import models


class OrderForm(forms.ModelForm):
    class Meta:
        model = models.Order
        fields = [
            'wave',
            'ct',
            'rt',
            'due_date',
            'saw',
            'bin',
            'bin_isle',
            'bin_column',
            'bin_row',
            'material',
            'thickness',
            'width',
            'length',
            'pulled',
            'delivered',
            'stock_ran',
        ]

orders_lite/views.py
# /orders_lite/views.py
from django.contrib.auth.decorators import login_required
from django.db.models import IntegerField
from django.db.models import Sum
from django.shortcuts import get_object_or_404
from django.shortcuts import redirect
from django.shortcuts import render

from orders_lite import forms
from orders_lite.models import Order


@login_required(login_url="accounts/login/")
def home(request):

    orders = Order.objects.all().order_by('wave__priority')
    picked_count = Order.objects.filter(picked=True).count()
    order_count = Order.objects.filter(picked=False, delivered=False, stock_ran=False).count()

    context = {
        "orders": orders,
        "picked_count": picked_count,
        "order_count": order_count,
    }
    return render(request, 'orders_lite/home.html', context)


@login_required(login_url="accounts/login/")
def order_create(request):
    if request.method == "POST":
        form = forms.OrderForm(request.POST or None, request.FILES)
        if form.is_valid():
            # Save to DB
            instance = form.save(commit=False)
            instance.employee = request.user
            instance.save()
            instance.save()
            return redirect('orders_lite:home')
    else:
        form = forms.OrderForm()

    context = {
        'form': form
    }
    return render(request, 'orders_lite/order_create.html', context)


def order_detail(request, slug):
    instance = Order.objects.get(slug=slug)
    context = {
        'instance': instance
    }
    return render(request, 'orders_lite/order_detail.html', context)


def order_delete(request, slug):
    instance = get_object_or_404(Order, slug=slug)
    if request.method == "POST":
        instance.delete()
        return redirect('orders_lite:home')

    context = {
        'instance': instance
    }
    return render(request, 'orders_lite/order_delete.html', context)


def home(request):
    orders = Order.objects.all().order_by('wave', 'due_date')
    context = {"orders": orders}
    return render(request, 'orders_lite/home.html', context)


@login_required(login_url="accounts/login/")
def order_edit(request, slug):
    instance = get_object_or_404(Order, slug=slug)
    form = forms.OrderForm(request.POST or None, instance=instance)
    if form.is_valid():
        # Save to DB
        instance = form.save(commit=False)
        instance.employee = request.user
        instance.save()
        return redirect('orders_lite:home')

    context = {
        'form': form,
        'instance': instance,
    }
    return render(request, 'orders_lite/order_edit.html', context)


@login_required(login_url="accounts/login/")
def order_duplicate(request, slug):
    instance = get_object_or_404(Order, slug=slug)
    form = forms.OrderForm(request.POST or None, request.FILES)
    if request.method == "POST":
        if form.is_valid():
            # Save to DB
            instance = form.save(commit=False)
            instance.employee = request.user
            instance.save()
            return redirect('orders_lite:home')
    else:
        form = forms.OrderForm(request.POST or None, request.FILES)

    context = {
        'form': form,
        'instance': instance,
    }
    return render(request, 'orders_lite/order_duplicate.html', context)

orders_lite/templates/orders_lite/components/nav_btn.html
{% load icons %}
<span class="text-center"><a href="{% url link %}" type="button"
                             class="text-center m-1 btn btn-primary">{% icon icon %} {{ title }}</a></span>

orders_lite/templates/orders_lite/components/order_accordion.html
{% load icons %}
<div class="accordion" id="alro-orders">
    <div class="card">
        <div class="card-header
            {% if order.wave == "cc" or order.wave == "ups" %}
                    bg-default
                    {% elif order.wave.name == "1st" %}
                    bg-success
                    {% elif order.wave.name == "2nd" %}
                    bg-warning
                    {% elif order.wave.name == "3rd" %}
                    bg-primary
                    {% elif order.wave.name == "4th" %}
                    bg-danger
                    {% endif %}
                    " id="headingOne-{{ order.pk }}"  data-toggle="collapse" data-target="#collapseOne-{{ order.pk }}">
            <h2 class="mb-0">
                <button class="btn btn-link"
                        {% if order.wave.name == "cc" or order.wave.name == "ups" %}
                        style="text-decoration: none; color: black"
                        {% else %}
                        style="text-decoration: none; color: white"
                        {% endif %}
                        type="button" data-toggle="collapse" data-target="#collapseOne-{{ order.pk }}"
                        aria-expanded="true" aria-controls="collapseOne-{{ order.pk }}">
                    CT {{ order.ct }} - {{ order.bin_name }}<br>{{ order.wave.name|upper }} - {{ order.wave.ship_time }}
                    <br>{{ order.saw }}
                </button>
            </h2>
        </div>

        <div id="collapseOne-{{ order.pk }}" class="collapse" aria-labelledby="headingOne-{{ order.pk }}"
             data-parent="#alro-orders">
            <div class="card-body">
                <div class="col-sm12 col-lg4">
                    <a href="{% url 'orders_lite:order_delete' slug=order.slug %}" class="btn btn-danger">{% icon 'trash' %}</a>
                    <a href="{% url 'orders_lite:order_edit' slug=order.slug %}" class="btn btn-success">{% icon 'edit' %}</a>
                    <a href="{% url 'orders_lite:order_detail' slug=order.slug %}" class="btn btn-primary">{% icon 'eye' %}</a>
                    {% include "orders_lite/components/order_barcode_group.html" %}
                </div>
            </div>
        </div>
    </div>
</div>

orders_lite/templates/orders_lite/components/order_barcode_group.html
<h4 class="text-center">CT {{ order.ct }}</h4>
<img class="pt-2" width="100%" src="{{ order.ct_barcode.url }}" alt="{{ order.ct }}">
<h4 class="text-center">RT {{ order.rt }}</h4>
<img class="pt-2" width="100%" src="{{ order.rt_barcode.url }}" alt="{{ order.rt }}">
<h4 class="text-center">{{ order.saw|upper }}</h4>
<img class="pt-2" width="100%" src="{{ order.saw_barcode.url }}" alt="{{ order.saw }}">
<h4 class="text-center">{{ order.bin_name }}</h4>
<img class="pt-2" width="100%" src="{{ order.bin_barcode.url }}" alt="{{ order.bin_name }}">

orders_lite/templates/orders_lite/components/order_list_btn.html
{% load icons %}

<div class="row">
    <a href="{% url 'orders:order_edit' slug=order.slug %}" class="m-1 btn bg-transparent">CT{{order.ct}}</a>
    <a type="button" class="m-1 btn bg-transparent">{{order.location_name}}</a>
    <a href="{% url 'orders:order_delete' slug=order.slug %}" class="m-1 btn bg-danger"> <i class="fas fa-trash"></i> </a>
    <img src="{{ order.barcode.url }}" alt="">
</div>

orders_lite/templates/orders_lite/components/table_ct.html
{% load icons %}
<div class="col-12 table-responsive-sm">
    <table class="table table-sm table-responsive">
        <thead>
            <tr>
                <th>CT Number</th>
                <th>{% icon 'barcode' %}</th>
                <th>RT Number</th>
                <th>{% icon 'barcode' %}</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td>CT{{order.ct}}</td>
                <td><a href="" class="btn btn-sm btn-warning">{% icon 'barcode' %}</a></td>
                <td>RT{{order.ct}}</td>
                <td><a href="" class="btn btn-sm btn-warning">{% icon 'barcode' %}</a></td>
            </tr>
        </tbody>
    </table>
</div>

orders_lite/templates/orders_lite/components/table_steel_attributes.html
<div class="col-12 table-responsive-sm">
    <table class="table table-sm table-responsive">
        <thead>
            <tr>
                <th>Thickness</th>
                <th>Width</th>
                <th>Length</th>
                <th>Weight</th>
                <th>Cut Sq-in</th>
                <th>Cross-cut Sq-in</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td>{{order.thickness}}</td>
                <td>{{order.width}}</td>
                <td>{{order.length}}</td>
                <td>{{order.weight|floatformat:0}} lbs.</td>
                <td>{{order.weight|floatformat:0}} lbs.</td>
                <td>{{order.weight|floatformat:0}} lbs.</td>
            </tr>
        </tbody>
    </table>
</div>