accounts/urls.py
# /accounts/urls.py
from django.conf.urls.static import static
from django.urls import path, include
from base import settings
from accounts.views import profile_view, guest_view, register_view, login_view, logout_view


app_name = 'accounts'

urlpatterns = [
    path('', profile_view, name="profile_view"),
    path('guest/', guest_view, name="guest_view"),
    path('profile/', profile_view, name="profile_view"),
    path('register/', register_view, name="register_view"),
    path('login/', login_view, name="login_view"),
    path('logout/', logout_view, name="logout_view"),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

base/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import include
from django.urls import path

from . import settings
from .views import home

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home, name="home"),
    path('orders/lite/', include('orders_lite.urls')),
    path('accounts/', include('accounts.urls')),
    path('locations/', include('locations.urls')),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models
from django.template.defaultfilters import slugify
from datetime import datetime
from django.contrib.auth.models import User

now = datetime.now() # current date and time
time = now.strftime("%H:%M:%S")


class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)

    location = models.CharField(max_length=30, blank=True, null=True)
    employee_number = models.IntegerField()
    work_shift = models.IntegerField(default=2)

    class Meta:
        ordering = ['user']
        verbose_name_plural = "User Profiles"
        verbose_name = "User Profile"

    def __str__(self):
        return self.user.username

    def save(self, *args, **kwargs):
        self.slug = slugify(self.user.username)
        super(UserProfile, self).save(*args, **kwargs)



class Account(models.Model):
    created = models.DateTimeField(auto_now_add=True)
    name = models.CharField(max_length=200, blank=True, null=True)
    slug = models.SlugField(blank=True, null=True)

    class Meta:
        ordering = ['name']
        verbose_name_plural = "Accounts"
        verbose_name = "Account"

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super(Account, self).save(*args, **kwargs)

accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.forms import ModelForm

from accounts.models import UserProfile


class ExtendedUserCreationForm(UserCreationForm):
    email = forms.EmailField(required=True)
    first_name = forms.CharField(max_length=30)
    last_name = forms.CharField(max_length=100)

    class Meta:
        model = User
        fields = ('username', 'email', 'first_name', 'last_name', 'password1', 'password2')

    def save(self, commit=True):
        user = super().save(commit=False)

        user.email = self.cleaned_data['email']
        user.first_name = self.cleaned_data['first_name']
        user.last_name = self.cleaned_data['last_name']

        if commit:
            user.save()
        return user


class UserProfileForm(ModelForm):
    class Meta:
        model = UserProfile
        fields = (
            'location',
            'employee_number',
        )

accounts/views.py
# /accounts/views.py
from django.contrib.auth import login
from django.contrib.auth import logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.forms import UserCreationForm
from django.shortcuts import redirect
from django.shortcuts import render


def guest_view(request):
    context = {}
    return render(request, 'accounts/guest.html', context)


@login_required(login_url="/accounts/login/")
def profile_view(request):
    context = {}
    return render(request, 'accounts/profile.html', context)


def register_view(request):
    form = UserCreationForm()

    if request.method == "POST":
        form = UserCreationForm(request.POST)

        if form.is_valid():
            user = form.save()
            # Log User in
            login(request, user)
            return redirect('accounts:profile_view')
        else:
            form = UserCreationForm()

    context = {'form': form}
    return render(request, 'accounts/register.html', context)


def login_view(request):
    if request.method == "POST":
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            # Log User in
            user = form.get_user()
            login(request, user)
            return redirect('accounts:profile_view')
    else:
        form = AuthenticationForm()

    context = {'form': form}
    return render(request, 'accounts/login.html', context)


def logout_view(request):
    if request.method == "POST":
        logout(request)
        return redirect('accounts:guest_view')
    return render(request, 'accounts/guest.html')

accounts/templates/accounts/guest.html
<!-- /accounts/templates/accounts/home.html -->
{% extends 'base.html' %}
{% load static %}

{% block content %}
<div class="container-fluid p-5">
    <h3 class='text-center'>Guest</h3>
</div>
<div class="container-fluid text-center">
    <a href="{% url 'accounts:register_view' %}" class="mb-2 col-sm-2 btn btn-primary">Register</a>
    <a href="{% url 'accounts:login_view' %}" class="mb-2 col-sm-2 btn btn-primary">Login</a>
</div>
{% endblock content %}

accounts/templates/accounts/login.html
{% extends 'base.html' %}

{% block content %}
<div class="container mt-5">
    <h3 class="text-center">Account Login</h3>
    <form action="{% url 'accounts:login_view' %}" method="POST">
        {% csrf_token %}
        {{form.as_p}}
        {% if request.GET.next %}
            <input type="hidden" value="{{ request.GET.next }}">
        {% endif %}
        <br>
        <input class="col-sm-2 btn btn-primary" type="submit" value="Login">
    </form>
</div>
{% endblock content %}

accounts/templates/accounts/profile.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<div class="container-fluid pt-3">
    <h3 class="text-center">{{user.first_name}} {{user.last_name}}'s Profile</h3>
</div>
<div class="container-fluid text-center">
<a href="{% url 'home' %}" class="btn btn-primary">Check Messages</a>
</div>
<div class="container-fluid">
<h3 class="text-center">Employee Number</h3>

<img src="" alt="">
</div>
<div class="container-fluid">
    <div class="container-fluid row">
        <div class="ml-4 col-sm-12 col-md-6 col-lg-3 card mt-3 pt-2">
        <h3 class="text-center"><span>{{ user.first_name }} {{user.last_name}}</span></h3>
        <h5 class="text-center">Employee #: 
        <button type="button" class="btn btn-primary btn-small p-1" data-toggle="modal" data-target="#employee_number{{ user.employee_number }}">
  Show
</button>
        </h5>
        <h5 class="text-center">G-South Crane #: 
        <button type="button" class="btn btn-primary btn-small p-1" data-toggle="modal" data-target="#crane20758">
  Show
</button>
        </h5>
    </div>
    </div>
</div>

<!-- Button trigger modal -->


<!-- EMPLOYEE NUMBER Modal -->
<div class="modal fade" id="employee_number{{ user.employee_number }}" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalCenterTitle">{{user.first_name}} {{user.last_name}} ({{ user.profile.employee_number }})</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <img src="../../../media/employee_number/Lee%20Laing.png" alt="">
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary p-1" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>


<!-- CRANE NUMBER Modal -->
<div class="modal fade" id="crane20758" tabindex="-1" role="dialog" aria-labelledby="crane20758Title" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="crane20758Title">{{user.first_name}} {{user.last_name}} (20758)</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <img width="100%" src="../media/inspections/crane-20758.png" alt="">
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary p-1" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>

{% endblock content %}

accounts/templates/accounts/register.html
{% extends 'base.html' %}

{% block content %}
<div class="container mt-5">
    <h3 class="text-center pb-5">Register New Account</h3>
    <form action="{% url 'accounts:register_view' %}" method="POST">
        {% csrf_token %}
        {{form.as_p}}
        <br>
        <input class="col-sm-2 btn btn-primary" type="submit" value="Register">
    </form>
</div>
{% endblock content %}

accounts/templates/accounts/user_badge.html
<div class="container-fluid">
<h4 class="text-center">{{ user.first_name }} {{ user.last_name }}</h4>
</div>