accounts/urls.py
# /accounts/urls.py
from django.conf.urls.static import static
from django.urls import path, include
from base import settings
from accounts.views import profile_view, guest_view, register_view, login_view, logout_view


app_name = 'accounts'

urlpatterns = [
    path('', profile_view, name="profile_view"),
    path('guest/', guest_view, name="guest_view"),
    path('profile/', profile_view, name="profile_view"),
    path('register/', register_view, name="register_view"),
    path('login/', login_view, name="login_view"),
    path('logout/', logout_view, name="logout_view"),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

base/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import include
from django.urls import path

from . import settings
from .views import home

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home, name="home"),
    path('orders/lite/', include('orders_lite.urls')),
    path('accounts/', include('accounts.urls')),
    path('locations/', include('locations.urls')),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

locations/urls.py
# /locations/urls.py
from django.conf.urls.static import static
from django.urls import path

from base import settings
from . import views

app_name = 'locations'

urlpatterns = [
    path('', views.locations, name="home"),
    path('g/', views.gbay_locations, name="gbay_locations"),
    path('c/', views.c_locations, name="c_locations"),
    path('b/', views.b_locations, name="b_locations"),
    path('cc/', views.cc_locations, name="cc_locations"),
    path('bph/', views.bph_locations, name="bph_locations"),
    path('cph/', views.cph_locations, name="cph_locations"),
    path('nwr/', views.nwr_locations, name="nwr_locations"),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

orders_lite/urls.py
# /orders_lite/urls.py
from django.conf.urls.static import static
from django.urls import path, include
from base import settings
from orders_lite.views import home, order_edit, order_duplicate, order_create, order_delete, order_detail

app_name = 'orders_lite'

urlpatterns = [
    path('', home, name="home"),
    path('create/', order_create, name='order_create'),
    path('<slug:slug>/', order_detail, name='order_detail'),
    path('<slug:slug>/edit/', order_edit, name='order_edit'),
    path('<slug:slug>/duplicate/', order_duplicate, name='order_duplicate'),
    path('<slug:slug>/delete/', order_delete, name='order_delete'),
]

base/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required


@login_required(login_url="/accounts/login/")
def home(request):
    context = {}
    return render(request, 'home.html', context)

templates/base.html
{% load static %} {% load humanize %} {% load icons %} {% load widget_tweaks %}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- font awesome -->
    <script src="https://kit.fontawesome.com/b4ac6ef2b3.js"></script>

    <!--Import Google Icon Font-->
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet" />

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

    <!-- Custom SASS (CSS) File -->
    <link rel="stylesheet" href="{% static 'accounts/css/accounts.css' %}">
    <link rel="stylesheet" href="{% static 'orders/css/orders.css' %}">


    <title>Material Handling App</title>
  </head>
  <header>{% include 'navbar.html' %}</header>
  <body>
    {% block content %} {% endblock content %}

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
    <script src="{% static 'accounts/js/accounts.js' %}"></script>

  </body>
</html>

templates/home.html
{% extends 'base.html' %}
{% load static %}
{% load icons %}

{% block content %}
<div class="jumbotron">
    <span><a class="btn btn-primary btn-sm" href="#current_messages" role="button">Messages</a></span>
    <span><a class="btn btn-primary btn-sm" href="{% url 'accounts:profile_view' %}" role="button">Profile</a></span>
  <h1 class="display-5">Welcomes back to ALRO Messages!</h1>
  <p class="lead">Good Afternoon {{user.first_name}}. Team Alro is glad to see you today and we personally want to thank you for all your hard work in meeting our team's goals!</p>
  <hr class="my-4">
  <p>Have a wonderful shift and day and please contact your shift supervisor for any issues or questions you may have while working today.</p>
  
</div>
<div id="current_messages" class="container-fluid">
    <div class="card m-2">
        <h3 class="text-center">Current Messages</h3>
        <div class="card m-3" style="width: 88%;">
            <div class="card-body">
                <h5 class="card-title">Card title</h5>
                <h6 class="card-subtitle mb-2 text-muted">Card subtitle</h6>
                <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
                <a href="#" class="card-link">Reply</a>
                <a href="#" class="card-link">Mark as Read</a>
            </div>
</div>
    </div>
</div>
{% endblock content %}

templates/navbar.html
{% load static %}
{% load icons %}
{% load account_tags %}

<nav class="navbar navbar-expand-lg navbar-dark bg-primary">
  {% navbar_brand_link 'home' %}
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'home' %}">{% icon 'home' %}</a>
      </li>
{#      <li class="nav-item">#}
{#        <a class="nav-link" href="{% url 'orders:home' %}">Orders</a>#}
{#      </li>#}
        <li class="nav-item">
            <a class="nav-link" href="{% url 'orders_lite:home' %}">Orders LITE</a>
        </li>

      <li class="nav-item">
        <a class="nav-link" href="{% url 'locations:home' %}">Locations</a>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Accounts
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          {% if not user.is_authenticated %}
          <a class="dropdown-item" href="#">Register</a>
          <a class="dropdown-item" href="{% url 'accounts:login_view' %}">{% icon 'sign-in-alt' %} Login</a>
          <div class="dropdown-divider"></div>
          {% else %}
          <a class="dropdown-item" href="{% url 'accounts:profile_view' %}">Profile</a>
          <div class="dropdown-divider"></div>
          <form action="{% url 'accounts:logout_view' %}" method="POST">
          {% csrf_token %}
            <button class="dropdown-item" type="submit">{% icon 'sign-in-alt' %} Logout</button>
          </form>
          {% endif %}
        </div>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="/admin">{% icon 'user-lock' %} Admin</a>
      </li>
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>